name: ItemLocator
version: '1.0'
main: com.shweit.itemlocator.ItemLocator
api-version: '1.21'
authors: [ Shweit ]

commands:
  itemlocator:
    description: "Main command for the ItemLocator plugin."
    usage: "/itemlocator"
    aliases: [ u ]
